version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-elementary
    environment:
      MYSQL_DATABASE: distribuidos
      MYSQL_USER: alan
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: alan
      PMA_PASSWORD: password
    ports:
      - "3001:80"
    depends_on:
      - mysql